### ISSUE TITLE
Could you please tag releases?

### ISSUE THREAD

**Issue by szepeviktor** [transcode-open/apt-cyg#34]
https://help.github.com/articles/creating-releases/

**Comment by svnpenn** [comment]
I dont really have an interest in doing this. If you could suggest some tag names, and what commits they would refer to, then I will consider it.

**Comment by szepeviktor** [comment]
It is enough to start at the next release.
The tag nam could be `v0.60`.

**Comment by svnpenn** [comment]
v0.59 is already a tag

http://github.com/transcode-open/apt-cyg/tags

**Comment by szepeviktor** [comment]
OK.

**Comment by svnpenn** [comment]
To any concerned, I have moved the current tags. We did a rebase a while back and since then they werent actually pointing to commits

**Comment by svnpenn** [comment]
To any concerned, I have moved the current tags. We did a rebase a while back and since then they werent actually pointing to commits. I also plan to add a couple more recent tags

**Comment by szepeviktor** [comment]
Thank you.
Please consider [semantic versioing](http://semver.org/). I even use it in my [bash scripts](https://github.com/szepeviktor/debian-server-tools/blob/master/security/fail2ban-leanmail/leanmail.sh#L5).
