### ISSUE TITLE
Enhancement Request: Implement equivalent of yum list installed

### ISSUE THREAD

**Issue by aware74** [transcode-open/apt-cyg#35]
This would allow me to query for whether a package is already installed within cygwin, without grepping the /etc/setup/installed.db repository myself.

Not only would it be a convenience, but it would allow developers to get back a zero return code for installed and a non-zero return code for not installed without knowing that /etc/setup/installed.db exists as an implementation detail.

It would also allow for a developer to write something like:

```bash
${pkgMgr} list installed ${pkgName}
```

This would provide the same exit code, regardless of whether `${pkgMgr}` were set to "yum", for example, on CentOS or RHEL, or set to "apt-cyg" on Cygwin.

Thanks in advance for your consideration.

Example yum output for comparison:

```bash
[user@computer ~]# yum list installed wget
Installed Packages
wget.x86_64 1.12-1.4.el6 @anaconda-RedHatEnterpriseLinux-201206132210.x86_64/6.3
[user@computer ~]# echo $?
0
[user@computer ~]# yum list installed some_unheard_of_package
Error: No matching Packages to list
[user@computer ~]# echo $?
1
```

Regards,
Mike

**Comment by svnpenn** [comment]
Correct me if I am wrong, but this is already available:

    apt-cyg list wget

**Comment by svnpenn** [comment]
@aware74 correct me if I am wrong, but this is already available:

    apt-cyg list wget

**Comment by svnpenn** [comment]
@aware74 correct me if I am wrong, but this is already available:

    apt-cyg list wget

Also, before you ask, I will not change it to `list installed`. Yes that would
make your script work with apt-cyg and yum, but it would still fail
spectacularly on apt-get, zypper and pacman. I will consider implementing an
exit code if you are still needing it.

**Comment by aware74** [comment]
I was able to achieve the behavior that I wanted locally.  Thank you.


Sent via the Samsung Galaxy Note® 3, an AT&T 4G LTE smartphone

-------- Original message --------
