### ISSUE TITLE
Install from list

### ISSUE THREAD

**Issue by nfarrar** [transcode-open/apt-cyg#45]
An enhancement request: it would be awesome if we could install from a package list, so a cygwin install could be *easily* migrated or rebuilt with:

    # dump list of installed packages
    apt-cyg list > packages.list

On a new system:

    apt-cyg install -f packages.list

**Comment by svnpenn** [comment]
I killed this with 3ca57e8, and frankly I have no interest in bringing it back. apt-get and pacman dont have it and I want to say zypper doesnt either.

As a workaround you can do

    apt-cyg list > packages.list
    apt-cyg install < packages.list
