### ISSUE TITLE
Update --version and years

### ISSUE THREAD

**Issue by zaroth** [transcode-open/apt-cyg#46]
when typing `apt-cyg --version` I still see the same thing as was there in `apt-cyg` not developed for years:

```
apt-cyg version 0.59

The MIT License (MIT)

Copyright (c) 2005-9 Stephen Jungels
```

While the old one is indistinguishable from this:

```
apt-cyg version 0.59
Written by Stephen Jungels

Copyright (c) 2005-9 Stephen Jungels.  Released under the GPL.
```

Please at least update the years in copyright so users can quickly check whether their tool is something not touched since 2009 or maybe it's actively developed.

**Comment by transcode-open** [comment]
Metabugs like this are a waste of time for the project maintainers, please don't file them.

**Comment by zaroth** [comment]
I'm not sure I understand - is there another place to file and track this? Or are you saying you guys don't care about informing users of the version of the software they're using?

**Comment by svnpenn** [comment]
@zaroth I am not interested in this issue. However if you submit a PR I will consider it. Please no more discussion on the matter.
