### ISSUE TITLE
Handle spaces

### ISSUE THREAD

**Issue by kenzierocks** [transcode-open/apt-cyg#50]
Currently it looks like spaces mess up apt-cyg a little bit:
```
mkdir: cannot create directory `/cygdrive/c/Users/Kenzie': Permission denied
/usr/bin/apt-cyg: line 149: cd: /cygdrive/c/Users/Kenzie/ftp%3a%2f%2fftp.gtlib.gatech.edu%2fpub%2fcygwin%2f/x86_64: No such file or directory
```

**Comment by svnpenn** [comment]
You have made a terrible comment. Not only are there no spaces in the output you have listed, but if the correct directory had spaces, you didnt list that either. On top of that the issue is with permissions and not spaces, as can be clearly seen. Just awful.

**Comment by kenzierocks** [comment]
Thanks, that was a really nice comment too :)

**Comment by kenzierocks** [comment]
Next time you can probably ask for info before just shutting this down.


Failing directory `/cygdrive/c/Users/Kenzie Togami/<probably more stuff>`. It says permission denied because there's no permission to create stuff in the `/cygdrive/c/Users/` directory by default, and it *wouldn't be doing that* if there was correct space handling. I fixed it myself by changing the cache directory, for any poor souls that come across this.

**Comment by svnpenn** [comment]
Howard said this years ago, and it still holds true:

> Some folks may think responses like this are uncalled for. Think again.

> You would not walk into the kitchen of a gourmet restaurant and ask the head 
> chef to teach you how to boil a pot of water. The question itself is rude; 
> it's inconsiderate of you to waste people's time with such questions that you 
> should have found the answer to long before.

> Every thing that I put out on the web is the result of intense thought. I 
> expect the same of all of you. Think before you post.

http://lists.mplayerhq.hu/pipermail/rtmpdump/2011-September/001618.html

**Comment by kenzierocks** [comment]
Fine. I will attempt to prove that it mishandles spaces.

**Comment by kenzierocks** [comment]
```
KenzieTogami@SILICON-CHIP-PC ~
$ apt-cyg cache '/cygdrive/c/Users/Kenzie Togami/cygwin'
Cache set to C:\Users\Kenzie Togami\cygwin.

KenzieTogami@SILICON-CHIP-PC ~
$ apt-cyg install python3
mkdir: cannot create directory `/cygdrive/c/Users/Kenzie': Permission denied
/usr/bin/apt-cyg: line 149: cd: /cygdrive/c/Users/Kenzie/ftp%3a%2f%2fftp.gtlib.gatech.edu%2fpub%2fcygwin%2f/x86_64: No such file or directory
Package python3 is already installed, skipping
```

This doesn't work.


```
KenzieTogami@SILICON-CHIP-PC ~
$ apt-cyg cache '/cygdrive/c/cygwin-cache'
Cache set to C:\cygwin-cache.

KenzieTogami@SILICON-CHIP-PC ~
$ apt-cyg install python3
--2015-05-30 19:49:08--  ftp://ftp.gtlib.gatech.edu/pub/cygwin//x86_64/setup.bz2
           => `.listing'
Resolving ftp.gtlib.gatech.edu (ftp.gtlib.gatech.edu)... 128.61.111.11, 128.61.111.9, 128.61.111.10, ...
Connecting to ftp.gtlib.gatech.edu (ftp.gtlib.gatech.edu)|128.61.111.11|:21... connected.
Logging in as anonymous ... Logged in!
```

This does work. What's up with that. I can create things in the correct directory `/cygdrive/c/Users/Kenzie Togami/` just fine:
```
KenzieTogami@SILICON-CHIP-PC ~
$ mkdir /cygdrive/c/Users/Kenzie\ Togami/directory

KenzieTogami@SILICON-CHIP-PC ~
$ mkdir /cygdrive/c/Users/Kenzie\ Togami/cygwin
```

**Comment by kenzierocks** [comment]
Thank you.
