### ISSUE TITLE
Cache Directory That Contains Space

### ISSUE THREAD

**Issue by willw64** [transcode-open/apt-cyg#53]
My cache directory is D:\Program Files\cygwin64，when I use apt-cyg to install package, it download package cache to D:\Program. I've seen the code of apt-cyg. You use awk print $1, which can only obtain D:\Program before the space. That cause this problem, hope you can fix it. Thank you!

**Comment by svnpenn** [comment]
I am closing this lazy post. If you can post an error message, or the code line in question, I will consider reopening it
