### ISSUE TITLE
bug $cache=/ no work + fix pull 55

### ISSUE THREAD

**Issue by andykimpe** [transcode-open/apt-cyg#56]
<code>$ apt-cyg update
mkdir: cannot create directory ‘//http%3a%2f%2fcygwin.mirror.constant.com%2f’: Read-only file system
/usr/bin/apt-cyg: line 149: cd: //http%3a%2f%2fcygwin.mirror.constant.com%2f/x86_64: No such file or directory
--2015-07-01 19:36:55--  http://cygwin.mirror.constant.com//x86_64/setup.bz2
Resolving cygwin.mirror.constant.com (cygwin.mirror.constant.com)... 108.61.5.83
Connecting to cygwin.mirror.constant.com (cygwin.mirror.constant.com)|108.61.5.83|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1417604 (1.4M) [application/octet-stream]
Saving to: ‘setup.bz2’

setup.bz2           100%[=====================>]   1.35M   653KB/s   in 2.1s

2015-07-01 19:36:57 (653 KB/s) - ‘setup.bz2’ saved [1417604/1417604]

Updated setup.ini</code>

patch pull 55 https://github.com/transcode-open/apt-cyg/pull/55

**Comment by svnpenn** [comment]
If you cant take the time to describe the problem (beyond a code dump), then I wont take the time to merge it.
