### ISSUE TITLE
setup.ini issue with current Cygwin release

### ISSUE THREAD

**Issue by DigitalArcSystems** [transcode-open/apt-cyg#57]
apt-cyg fails to work on the latest cygwin x86_64 (and probably x86) branches.  This appears to be a repeat of:

https://code.google.com/p/apt-cyg/issues/detail?id=23

A quick Google search reveals this as a patch:

wget http://apt-cyg.googlecode.com/svn/trunk/apt-cyg
  sed -e 's%wget -N \$mirror/%&x86/%' -i apt-cyg #https://code.google.com/p/apt-cyg/issues/detail?id=23

Fix should be made permanently.

Steps to reproduce are as follows.  Install Cygwin... 

```
das@NEX ~
$ lynx -source rawgit.com/transcode-open/apt-cyg/master/apt-cyg > apt-cyg

das@NEX ~
$ install apt-cyg /bin

das@NEX ~
$ rm apt-cyg

das@NEX ~
$ apt-cyg install nano
wget is not installed, using lynx as fallback
bunzip2: setup.bz2 is not a bzip2 file.
mv: cannot stat `setup': No such file or directory
Updated setup.ini
Installing nano
awk: fatal: cannot open file `setup.ini' for reading (No such file or directory)

Unable to locate package nano

```

**Comment by svnpenn** [comment]
Sorry bro, cannot replicate. If you can demonstrate how I can reliably replicate this issue, I will consider reopening. Also do not link to or discuss the Google project. It is and has been dead for some time.

~~~
$ apt-cyg install nano
Installing nano
wget is not installed, using lynx as fallback
nano-2.4.1-1.tar.xz: OK
Unpacking...
Package nano requires the following packages, installing:
file libintl8 libncursesw10 _update-info-dir cygwin
[...]
Package nano installed
~~~
