### ISSUE TITLE
Spurious line-ending issue

### ISSUE THREAD

**Issue by thoni56** [transcode-open/apt-cyg#62]
I downloaded and installed apt-cyg exactly according to the instructions ('lynx...' & 'install...') and got
/usr/bin/apt-cyg: rad 25: $'\r': command does not exist
/usr/bin/apt-cyg: rad 106: $'\r': command does not exist
/usr/bin/apt-cyg: rad 114: $'\r': command does not exist
/usr/bin/apt-cyg: rad 115: syntax error near unexpected synbol "$'{\r'"
'usr/bin/apt-cyg: rad 115: `function wget {

A dos2unix solved that problem. My mount says

C:/cygwin/bin on /usr/bin type ntfs (binary,auto)
C:/cygwin/lib on /usr/lib type ntfs (binary,auto)
C:/cygwin on / type ntfs (binary,auto)
C: on /cygdrive/c type ntfs (text,posix=0,user,noumount,auto)

**Comment by svnpenn** [comment]
Nope. Not possible. apt-cyg uses LF line endings, I am certain of this. The instructions if followed will preserve this. If you can list steps to reproduce, I will consider reopening.

**Comment by svnpenn** [comment]
Nope. Not possible. apt-cyg uses LF line endings, I am certain of this. The instructions if followed will preserve this. If you can list steps to reproduce, I will consider reopening.

Also I see you are using Cygwin 32-bit. Stop doing that.

**Comment by svnpenn** [comment]
This is caused by your text mount on `C:`.

Frankly I have no interest in fixing this. As I see it, you broke your system by
using a text mount, I shouldnt be apt-cyg’s job to fix it. If you can provide a
compelling reason why we should support this and/or a patch, I will consider
reopening.

Also stop using Cygwin 32-bit. 64-bit CPUs have been available for PCs for about
12 years now.

**Comment by thoni56** [comment]
I'm ok with knowing that it is the text mount that is causing the issue and will be handling apt-cyg according to that information, thanks.

Although Cygwin's official take on the matter is AFAICS not that text mode is broken:

> Binmode is the best choice usually since it's faster and easier to handle, unless you want
> to exchange files with native Win32 applications.

I respect your view in the matter and the choice you've made for apt-cyg.

Me using a 32-bit OS is irrelevant and not your concern since you don't know the context.
