### ISSUE TITLE
 Permission denied Problem

### ISSUE THREAD

**Issue by yhllovezxl** [transcode-open/apt-cyg#65]
I'm use the apt-cyg install,the terminal promopt "-bash: /usr/bin/apt-cyg: Permission denied",i can't use it,please tell me the method.thank you.

**Comment by VarunAgw** [comment]
Check if you have read and execute permission to the file `ls -l /usr/bin/apt-cyg`

**Comment by svnpenn** [comment]
Perhaps next time, visit the readme before creating an issue.

http://github.com/transcode-open/apt-cyg/blame/395caa/README.md#L65

**Comment by vinchuco** [comment]
if windows, find apt-cyg file, right click, properties, security, click on user, click full control﻿, hit ok, restart your terminal and try again
