### ISSUE TITLE
Tab Completion

### ISSUE THREAD

**Issue by VarunAgw** [transcode-open/apt-cyg#66]
It will be great if we can have tab completion feature in it

**Comment by svnpenn** [comment]
I am not interested in implementing this feature. However some options are available:

- if other users comment in support I will reconsider
- if pull request is submitted I will consider
- if bounty is submitted I will consider

**Comment by VarunAgw** [comment]
Actually I was thinking of submitting a PR for it.

Right now, I have created a very simple script. It can of course be improved a lot

	#/etc/bash_completion.d/apt-cyg

	_apt_cyg()
	{
		COMPREPLY=()
		_get_comp_words_by_ref cur

		if [ $COMP_CWORD -eq 1 ]; then
			COMPREPLY=( $( compgen -W 'install remove update download show depends rdepends list listall category listfiles search searchall mirror cache --no-deps --version' -- "$cur" ) )
			return 0
		fi

	}

	complete -F _apt_cyg apt-cyg

**Comment by svnpenn** [comment]
@VarunAgw that looks simple enough. If you submit a PR I will strongly consider it, thank you.
