### ISSUE TITLE
wget is not installed, using lynx as fallback

### ISSUE THREAD

**Issue by vipzrx** [transcode-open/apt-cyg#68]
kk@x200 ~
$ apt-cyg update
wget is not installed, using lynx as fallback
Updated setup.ini

kk@x200 ~
$ apt-cyg install wget
Package wget is already installed, skipping

kk@x200 ~

**Comment by vipzrx** [comment]
kk@x200 ~
$ apt-cyg  --version
apt-cyg version 0.59

The MIT License (MIT)

Copyright (c) 2005-9 Stephen Jungels

**Comment by svnpenn** [comment]
Sorry, I cannot duplicate this issue. Also I do not take kindly to code dumps. Good day.
