### ISSUE TITLE
Error message "Unary operator expected" with new version

### ISSUE THREAD

**Issue by Lucas-C** [transcode-open/apt-cyg#71]
I have the following error messages using the latest `apt-cyg` when installing packages :
```
apt-cyg: line 468: [: -v : opérateur unaire attendu
apt-cyg: line 495: [: -v : opérateur unaire attendu
```

Apart from those log lines, everything seems to work fine.

**Comment by Lucas-C** [comment]
The error seems to come from the following lines:
```
[ -v nodeps ] && continue
[ -v noscripts ] && continue
```
which where introduced in commit 395caa566e6d65963a83043346b95064cfe74f24

**Comment by Lucas-C** [comment]
I'm using Bash v4.1 btw

**Comment by svnpenn** [comment]
Um, no? Bash 4.2 has been available since 2011:

http://ftp.gnu.org/gnu/bash

Update your system and stop wasting my time.

**Comment by Lucas-C** [comment]
I did not realize I was wasting your time by reporting this backward compatibility issue.
In case anyone else stumble on the same error message, I'm going to add a few more details here. Sorry if this consumes even more of your precious time.

The `-v` operator was introduced in bash 4.2 : http://tiswww.case.edu/php/chet/bash/NEWS.
It is not documented in `man test`.

If, like in my case, you cannot simply "upade your system", you can use an older `apt-cyg` version (e.g. the one at commit a517b08c9452e12dec4381efeb2f7b4859dc8bc5), or even better simply replace those lines in the `apt-cyg` script by backward compatible instructions :
```
sed -i 's/\[ -v /[ -n $/' apt-cyg
```

**Comment by svnpenn** [comment]
@Lucas-C I think you forgot that I can remove comments. Cheers!

**Comment by svnpenn** [comment]
https://github.com/transcode-open/apt-cyg/pull/72
