### ISSUE TITLE
Don't work in 64-bit applications

### ISSUE THREAD

**Issue by ercpereda** [transcode-open/apt-cyg#77]
I got the following error when I try to execute it

The program or feature "\??\C:\cygwin64\bin\apt-cyg.exe" cannot start or run due to incompatibility with 64-bit version of Windows. Please contact the software vendor to ask if a 64-bit Windows compatible version is available

**Comment by kou1okada** [comment]
Why did you append ".exe" extension?
Remove it, because apt-cyg is bash script.

**Comment by vbalasu** [comment]
To elaborate on @kou1okada , you probably got this error because you tried to launch apt-cyg.exe directly from the Windows command prompt. You have to first launch the Cygwin bash shell (usually c:\cygwin64\Cgywin.bat), then run apt-cyg within it. Hope this helps.

**Comment by kou1okada** [comment]
Thanks, @vbalasu ;-)
